### ISSUE TITLE
Demonstrating the Project on my interview

### ISSUE THREAD

**Issue by osherh** [TechnionYP5777/Info-Evaluation#106]
I was interviewed today by @AdiOmari , @orimarco. During the interview they wanted to run the project from their computers. I told them that since we run a server on a local host they need to install it on their machines first, so they moved to other questions. I wanted to add that we got our instructor's(yoav) permission to use a local host for this sprint. We searched for remote server alternatives and couldn't find a free one. I asked the staff on both github and facebook about the option that the lab would pay for the account. A week ago yossi gil told me to contact tom palny who suggested we use heroku. We decided to move the transaction for next sprint.

**Comment by zahimizrahi** [comment]
Parse server on heruko environment is my best recommendation. It's very easy to handle, and it will let you focus more on the front end.
However, you should know how to use it right. there's this [wiki](https://github.com/TechnionYP5777/SmartCity-ParkingManagement/wiki/Parse-Server-and-Heroku-environment) we wrote.

If you team needs help, you can contact @shaysegal  or @sefialbo who would be glad to help. Shay & Sefi set up the server for our project.

**Comment by yossigil** [comment]
FYI: @idabran @AdiOmari @yh-github @orimarco @TomPalny 
@osherh : will be discussed.
