### ISSUE TITLE
Your project does not use maven properly. Errors in import maven project

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Info-Evaluation#108]
![image](https://cloud.githubusercontent.com/assets/12775400/22335562/d727cfb4-e3e7-11e6-9ca5-8f2e8a9e3086.png)

You **cannot** correct this in this semester.

@TomPalny @AdiOmari @orimarco @idabran @yh-github

**Comment by SlasherTech** [comment]
solved #115
