### ISSUE TITLE
28.11 Meeting Summary

### ISSUE THREAD

**Issue by viviansh** [TechnionYP5777/Info-Evaluation#11]
-Logical partitioning of the project : 
Web Crawler -> Parsing and formatting the input for analysis -> Analyzing the text -> Store results in DB

-Missions for this week:
1. Choose WC and run it for a simple example,
2.Parse and format the input.
3.Analyze a simple paragraph for the use case of arrested celebrities.

Use Cases :
1.A journalist is looking for data about celebrities who got arrested lately.
2.Cars salesman is looking for the upcoming cars in 2017.
3.A real estate agent is looking to evalutate a luxury house price.

Update : 
Two teams were formed:
1. Input analyze - @geniashand @NetanelFelcher @MosheEliasof
2.GUI - @viviansh @ward-mattar @osherh

**Comment by yossigil** [comment]
Don't use label instead of milestone.

**Comment by yossigil** [comment]
You cannot have issue with six people assigned to it!

@zvili @idabran @yh-github @orimarco @AdiOmari
