### ISSUE TITLE
New queries to focus on in this semester

### ISSUE THREAD

**Issue by NetanelFelcher** [TechnionYP5777/Info-Evaluation#112]
In this semester we will focus on queries that their results are based on Wikipedia.
We will get the information by Web Crawler/ DBpedia.

we suggested the following queries:
 
- [x]  People who lived /were born/died  in certain years/periods.
- [x]  People who were born in (country).
- [x] People who have relatives that their occupation is (occupation).
- [x] People who won prizes in a specific field.
- [x] People who were murdered (with options to specify the search by occupation, year, place etc.)
 @geniashand  @viviansh  @osherh  @MosheEliasof 

@yh-github 
Yoav- as our customer, we would like you to give us a feedback on our suggestions so we can start work.
In addition, we thought of implementing UI with web interface, we would like to know your opinion about it.

**Comment by yh-github** [comment]
Hi, any of the queries will do. The main focus should be to allow interactivity and incremental structuring of the query/results. Of course, the GUI should be intuitive enough for a first time user.
