### ISSUE TITLE
Open a new Maven project and organize files.

### ISSUE THREAD

**Issue by SlasherTech** [TechnionYP5777/Info-Evaluation#115]
Due to the changes this semester, we will organize our project differently : 
- Open a new,clean Maven project.
-The project will include two subdirectories - one for the GUI and one for the WC (web crawler).
-The files from last semester will be zipped and stored , for later usage (e.g - after parsing Wikipedia pages, we might want to analyze them using CoreNLP. Therefore, the code from last semester would be useful.)

**Comment by SlasherTech** [comment]
Opened a new project, zipped files from previous semester.
Now we discuss of the structure of the classes and then this issue is resolved.

**Comment by yossigil** [comment]
:+1:
