### ISSUE TITLE
Wiki data design 

### ISSUE THREAD

**Issue by NetanelFelcher** [TechnionYP5777/Info-Evaluation#118]
In this issue we will describe the work that has to be done in the WikiData side, which has 2 parts:
- extracting the list of information from DBpedia and query on it.
- extracting specific entries from Wikipedia and Parsing it.

Each sub-issue regarding this part will be mentioned here in order to see the working plan clearly.

This is an abstract issue so there is no milestone for it.

**Comment by yossigil** [comment]
:+1:

**Comment by NetanelFelcher** [comment]
first stage: Extract data from DBpedia to our private data base #123

**Comment by NetanelFelcher** [comment]
next: store the data we extracted in our mySql server #136
