### ISSUE TITLE
Analyzing Paragraph

### ISSUE THREAD

**Issue by SlasherTech** [TechnionYP5777/Info-Evaluation#12]
I uploaded our work so far for the class which analyzes a paragraph and should return the name(of the main person in this paragraph),date and details of the paragraph.

@ward-mattar @viviansh @osherh : Notice that you have warnings and errors in your code. Please fix it.

**Comment by SlasherTech** [comment]
@geniashand Notice the comment in AnalyzeParagraph .Your date code isn't finished yet.

**Comment by geniashand** [comment]
@MosheEliasof notice new class AnalyzeDate was added. You can now use this class in your code

**Comment by SlasherTech** [comment]
Ready for sprint 1.
