### ISSUE TITLE
Plan the design for GUI views

### ISSUE THREAD

**Issue by geniashand** [TechnionYP5777/Info-Evaluation#121]
There is a need to plan ahead how the view of the GUI will look. This design may change during the semester if users may find it not intuitive enough

**Comment by SlasherTech** [comment]
My suggestion:
The GUI should let the user type the query ,or at least let the user specify some input.
For example : if the query regards to people who were born before a ceratin year, then the user can type/choose the desired year.

This is, unlike the GUI from last semester, a more user-involving and friendly GUI.

**Comment by geniashand** [comment]
As decided in the meeting the screen will be as follows:

- The main screen will contain a button for each query
![image](https://cloud.githubusercontent.com/assets/23057153/24743569/659d8d1e-1ab7-11e7-91d3-f725a5aca5b3.png)

- The screen of the first query which is "People who were born before ____ in _____". The empty places will be text boxes
![image](https://cloud.githubusercontent.com/assets/23057153/24743763/196cda02-1ab8-11e7-8a63-5fb10fa2d13b.png)

- After pressing the send button the user will be redirected to the screen below which contains a table
![image](https://cloud.githubusercontent.com/assets/23057153/24743827/63e2a990-1ab8-11e7-9af5-8a6a592b4197.png)

- The screen of the second query which is "People who died not in the same place they were born in"
![image](https://cloud.githubusercontent.com/assets/23057153/24743894/ae3e125e-1ab8-11e7-95fc-d45ba9a6a9e0.png)
