### ISSUE TITLE
Project Meeting - 5.4.17

### ISSUE THREAD

**Issue by SlasherTech** [TechnionYP5777/Info-Evaluation#124]
@geniashand @NetanelFelcher and I met and discusses about the following topics : 

- GUI design - how should it look like, and what it should contain and its functionality. ( #121 )

- Queries for current sprint - 2 queries which do not involve NLP , as arranging the data for is more complicated than extracting data from DBpedia. see issue #123  (We also work on parsing Wikipedia pages for NLP input in the same time . see issue #119)

The queries we will focus currently are : 
1.People who were born in a certain place before a certain year (the location and year are user-specified).
2.People who died in a different place than the one they were born in.
We will open an issue for each query for the GUI and analysis parts.

**Comment by yossigil** [comment]
:+1:
