### ISSUE TITLE
Creating the screen of the first query

### ISSUE THREAD

**Issue by osherh** [TechnionYP5777/Info-Evaluation#135]
The first query is "People who were born before ____(year) in _____(place/state)". The year and place will be entered to a text box  
(Later may want to change the place textbox to autocomplete text box)

**Comment by geniashand** [comment]
Currently reading [this tutorial](https://www.tutorialspoint.com/ionic/ionic_content.htm) in order to create the desired screen

**Comment by geniashand** [comment]
[This](https://www.tutorialspoint.com/ionic/ionic_buttons.htm) may be good for later color changes and style changes to the button. Currently I'm focusing on the basics, what we need in the screen. Later some colors will be added
