### ISSUE TITLE
Store data in mySql server

### ISSUE THREAD

**Issue by NetanelFelcher** [TechnionYP5777/Info-Evaluation#136]
We will run our queries on our mySql server (remote server) which will contain all the data
we extracted from DBpedia. 
We will store the data in a uniform way in order to be able to get the most accurate 
results for our queries (especially relevant for places and dates).
The data is supplied from the Extractor class.

**Comment by NetanelFelcher** [comment]
@osherh Can this issue be closed? I think all the data is already stored in the server...

**Comment by osherh** [comment]
The current impl catches most of the data, however there are still cases it fails to catch. I'll open an issue about it. You can close.
