### ISSUE TITLE
Setting-Up MySQL DB 

### ISSUE THREAD

**Issue by viviansh** [TechnionYP5777/Info-Evaluation#14]
How to setup local MySQL database, step by step.
see #13

**Comment by yossigil** [comment]
How would we know that this is done? What't he deliverable?
Who is assigned?

**Comment by osherh** [comment]
Steps: 
1. Install MySQL:
run the following commands:
sudo apt-get update
sudo apt-get install mysql-server
sudo mysql_secure_installation
can check your version of MySQL by running: mysql --version 
2. make sure pom.xml contains the mysql dependency
3. connect to the MySQL DB by running: mysql -u root -p
4. to run a sql script use: source <path_to_file> file.sql
