### ISSUE TITLE
Queries for refinements

### ISSUE THREAD

**Issue by viviansh** [TechnionYP5777/Info-Evaluation#15]
Define DB name, tables, build queries for refinements.
Write RefineTable class, which uses SQL queries for filtering the list of arrested celebrities by date, name or reason for.
see #13

**Comment by yossigil** [comment]
I am not sure I understand what's the deliverable? How do we know that this issue ends?
@AdiOmari @yh-github @zvili @orimarco @idabran

**Comment by yossigil** [comment]
Don't use label instead of milestone.

**Comment by viviansh** [comment]
This will be done after we have all the queries for refinement. @yossigil

**Comment by yossigil** [comment]
Remove the inappropriate label.
Describe this issue. It is impossible to understand now.
