### ISSUE TITLE
Build GUI components

### ISSUE THREAD

**Issue by viviansh** [TechnionYP5777/Info-Evaluation#16]
Write GUI class that implements the GUI, it should contain a text field to accept 
the user query, search/refine buttons and a table to hold the data
see #13

**Comment by yossigil** [comment]
I am not sure I understand what's the deliverable? How do we know that this issue ends?
@AdiOmari @yh-github @zvili @orimarco @idabran

**Comment by yossigil** [comment]
Don't use label instead of milestone.
