### ISSUE TITLE
Link GUI with SQL functions

### ISSUE THREAD

**Issue by viviansh** [TechnionYP5777/Info-Evaluation#17]
GUI component, as defined in #16, should be able to interact with the user, 
it should have support for sorting the presented events by: name, date and reason for accident.
 
Call SQL functions as defined in #15 and built according to #14 from GUI and apply appropriate updates to the event list.

see #13

**Comment by yossigil** [comment]
How/when will this end?
Who is in the assignee?
What's the milestone?
