### ISSUE TITLE
tableTuple and DataList

### ISSUE THREAD

**Issue by NetanelFelcher** [TechnionYP5777/Info-Evaluation#18]
The table tuple class represents a tuple in the final table that is shown to the user.

The DataList class represents the whole table. This is a list of tableTuple items.

The list with the data is the integration point between the analyzing part and the GUI part.

**Comment by yossigil** [comment]
:-1: 
Cryptic issue. I have no idea what it is supposed to do, when we will know it is done, etc.
Also, DO NOT USE labels for milestones.

@AdiOmari @yh-github
