### ISSUE TITLE
AnalyzePage class

### ISSUE THREAD

**Issue by geniashand** [TechnionYP5777/Info-Evaluation#20]
Writing a class that represents an article that needs to be analyzed according to the query the user entered. The class needs to have a method able to recognize paragraphs in the article in order to analyze them using the AnalizeParagraph class described in issue #12

**Comment by NetanelFelcher** [comment]
Note that the class name should be AnalyzePage

**Comment by NetanelFelcher** [comment]
You have committed a failing test... :(
