### ISSUE TITLE
AnalyzeSources class

### ISSUE THREAD

**Issue by NetanelFelcher** [TechnionYP5777/Info-Evaluation#21]
A class whose goal is to do the analysis on all the sources that are relevant to the query that was entered by the user. Each source is analyzed by using AnalyzePage class #20 .
This class uses all the DataLists from AnalyzePage and merge them into one list of all the data, so it can be provided to the GUI in order to show the information to the user.

**Comment by yossigil** [comment]
Note the typo in the class name
