### ISSUE TITLE
Convert project to maven

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Info-Evaluation#22]
- [x] Create a BLOCKER label
- [x] Paint it black
- [x] Attach to this issue
- [x] Create milestone if necessary
- [x] Assign for someone to do this.

I do not know who is in charge, so I picked one name at random.

**Comment by NetanelFelcher** [comment]
It will be appreciated if you don't open issues in Shabbat @yossigil

**Comment by yossigil** [comment]
Is this a matter of Maase Shabbat? If so, we need to discuss this. I do not want to hurt anyone's religous feelings.

If not, feel free to give me a ring, and we can discusss this. At any rate, opening and issue on Shabbos does not mean you have to do it on Shabbos.

**Comment by NetanelFelcher** [comment]
It is a matter of giving equal opportunities to all. Opening a new issue on Shabbos prevents me from getting updated at the same time like everybody else.

**Comment by yossigil** [comment]
Good point!

In this case though, since I do not know you guys, I picked out a random name, `I do not know who is in charge, so I picked one name at random.` So, you did not loose much. In general you are not expected to work on weekend, nor will I allow any discrimination against anyone for a reason such as this.

I will keep your point in mind. Thanks for brinigng this up!
