### ISSUE TITLE
Show More Info button doesn't work for some people

### ISSUE THREAD

**Issue by osherh** [TechnionYP5777/Info-Evaluation#250]

**Comment by geniashand** [comment]
For some people the PersonalInformation web service works but for others it doesn't. I've noticed that most of the names work, however some names are still problematic. That may be a problem in the backend, can you write tests and see what's the problem?

**Comment by osherh** [comment]
I'm on it 
* Yossi PIamenta isn't in our DB

**Comment by osherh** [comment]
Yes, i'm on it

**Comment by geniashand** [comment]
Problem resolved
