### ISSUE TITLE
analysis of a page's details by paragraphs 

### ISSUE THREAD

**Issue by geniashand** [TechnionYP5777/Info-Evaluation#27]
Get details about events described in a given text which is dealt in class AnalyzePage #20. The current task needs to use the AnalyzeParagraph class #12 in order to get the analysis

Update:
Code checked on one paragraph and working. We need to see if it works on analysis of a text consisting multiple paragraphs

**Comment by yossigil** [comment]
@geniashand: take note that you can use `closes #IssueNumber` in your commit message. More information is available [here](https://help.github.com/articles/closing-issues-via-commit-messages/). 

@yh-github @orimarco @AdiOmari @idabran @zvili
