### ISSUE TITLE
Giving a wiki writing permission 

### ISSUE THREAD

**Issue by ravivos** [TechnionYP5777/Info-Evaluation#291]
Hey, you didn't explain how to get permissions to write wikis in your project.
I would like some in order to write the "Experience in Installation of Raviv Rachmiel" wiki

**Comment by NetanelFelcher** [comment]
None of us has an admin access. We are working on it

**Comment by roy-shchory** [comment]
i also nedd access to write wikis

**Comment by NetanelFelcher** [comment]
Try to add wikis now

**Comment by ravivos** [comment]
Doesn't work, please reopen
