### ISSUE TITLE
error when trying to load data 

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/Info-Evaluation#292]
steps to recreate :
1. open the app
2. press on Immigrated 
3. waited...
4. got that alert
![screenshot_2017-07-02-12-46-52](https://user-images.githubusercontent.com/15847157/27768831-2fd7fa90-5f25-11e7-9583-b192fffb6775.png)

**Comment by NetanelFelcher** [comment]
are you connected to a Technion network?

**Comment by shaysegal** [comment]
now connected, and works ! thanks i thought that the android i used wan connect ... ![bitmoji](https://render.bitstrips.com/v2/cpanel/7834193-204257602_3-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by NetanelFelcher** [comment]
great

**Comment by shaysegal** [comment]
it happend again ... im connect to cs-conference clicked on Immigrated than sergei Yudin then back and then it load for a long time and show that alert...

**Comment by NetanelFelcher** [comment]
I just checked it and it worked. Try connecting to students wifi

**Comment by NetanelFelcher** [comment]
solved?

**Comment by shaysegal** [comment]
yes , i didn't got it again
