### ISSUE TITLE
Ambiguity bug 

### ISSUE THREAD

**Issue by roy-shchory** [TechnionYP5777/Info-Evaluation#294]
i had an ambiguity on the query "comedy , louie" and got an ambiguity alert, moved to the choose the person screen.
nothing loaded and then the app crashed

**Comment by NetanelFelcher** [comment]
working on it

**Comment by koralchapnik** [comment]
+1

**Comment by yosefraisman** [comment]
The app doesn't crash for `Perform`, `Emma`, but the list comes up empty.

**Comment by NetanelFelcher** [comment]
The app is designed basically for specific persons (celebrities etc.)
Try to enter full names and see what happens
