### ISSUE TITLE
bug in immigrated

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/Info-Evaluation#296]
when trying to enter the immigrated functionality, and entering place of birth - 111
and year 111 the app is stuck in the spinner and it didn't dissapear.

**Comment by koralchapnik** [comment]
and when closing the app and entering again, the spinner still shows

**Comment by SlasherTech** [comment]
This is not a bug.
You need to be connected a technion wifi (NOT techPUBLIC)

**Comment by koralchapnik** [comment]
thanks
