### ISSUE TITLE
Bug when entering Immegrated

### ISSUE THREAD

**Issue by ravivos** [TechnionYP5777/Info-Evaluation#299]
https://www.dropbox.com/s/rfd7v2rcbxchcog/Screenshot%202017-07-02%2013.15.59.png?dl=0
link above has a screenshot of the bug - you exposed the get request when error fetching

**Comment by SlasherTech** [comment]
You aren't connected to a technion net.
You MUST be connected to students wifi . TechPUBLIC is not good !

**Comment by ravivos** [comment]
I am connected to Technion Public

**Comment by ravivos** [comment]
Ok, I will change my network, thank you
