### ISSUE TITLE
When entering a name with a typo

### ISSUE THREAD

**Issue by ravivos** [TechnionYP5777/Info-Evaluation#302]
when Entering a name with a typo I get a fetch error exception, instead of just showing an empty list or something not as scary as an error message dialog:
https://www.dropbox.com/s/7r19w0yv7vg30qy/Screenshot%202017-07-02%2013.54.04.png?dl=0

**Comment by SlasherTech** [comment]
dont be afraid. the system just tells you that it can't find the required information (because it is not found in wikipedia)

**Comment by geniashand** [comment]
can you please write the actions you've made in order to get there? When I write a name with a typo this message appears
![image](https://user-images.githubusercontent.com/23057153/27769285-927a0a58-5f2f-11e7-8818-90def74b14ac.png)

**Comment by NetanelFelcher** [comment]
now a new message is shown - the person couldn't be found in Wikipedia. 
This message covers incidents of typo errors and correct names of persons which don't have Wikipedia page as well

**Comment by ravivos** [comment]
Great, thanks
