### ISSUE TITLE
when asking for arrests about a person - shows also irrelevant arrests

### ISSUE THREAD

**Issue by ravivos** [TechnionYP5777/Info-Evaluation#306]
when asking for arrests about a person - shows also irrelevant arrests, for example, I got this irrelevant arrest when looking up for Mark Zuckerberg’s arrest https://www.dropbox.com/s/gsazjvdt4ias2mg/Screenshot%202017-07-02%2014.07.54.png?dl=0

**Comment by SlasherTech** [comment]
This is relevant.
The point is to show all the relevant data to the person and the query.
It DOES NOT neccesarily mean the person itself did/experienced the event , but also that it has relation to it.

**Comment by ravivos** [comment]
What is the relation overhere?

**Comment by ravivos** [comment]
In my opinion this should have been combined with one of the other arrest boxes of info, shouldnt it?

**Comment by SlasherTech** [comment]
The relation is Mark Zuckerberg's partner for founding facebook is Celiga.

For your second comment - I simply do not understand what you're trying to say. Please rephrase.
