### ISSUE TITLE
When looking for a person with the correct name but no arrests - says I have a typo

### ISSUE THREAD

**Issue by ravivos** [TechnionYP5777/Info-Evaluation#307]
9. When looking for a person with the correct name but no arrests - says I have a typo instead of showing a no arrests window - i.e, this is what I get when looking for myself, Raviv Rachmiel: https://www.dropbox.com/s/shq2n6xjcfhvdaz/Screenshot%202017-07-02%2014.10.40.png?dl=0

**Comment by NetanelFelcher** [comment]
note my comment in the typo issue. In the next apk release the message will be different.
