### ISSUE TITLE
example query doesn't work

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/Info-Evaluation#308]
try + and then choose "speech" , "Donuld Trump" and didnt work... http://imgur.com/GGP7szy

**Comment by NetanelFelcher** [comment]
You have a typo error. try "Donald Trump"

**Comment by shaysegal** [comment]
K , so you have this typo in the exmple it worte "Donuld Trump"

**Comment by NetanelFelcher** [comment]
You are right. fixing it
