### ISSUE TITLE
Support adding DataList to MySQL database via Java code

### ISSUE THREAD

**Issue by ward-mattar** [TechnionYP5777/Info-Evaluation#31]
Implement a method at MySQLConnector that gets DataList and
inserts it to 'events' table at 'celebs_arrests' database

**Comment by yossigil** [comment]
@yh-github : you may want to advise them to search a bit for a library for such things.

**Comment by ward-mattar** [comment]
@osherh: Added support of date conversion from MM/dd/yyyy -> yyyy-MM-dd
