### ISSUE TITLE
back button in main page return to query even if it is problematic query 

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/Info-Evaluation#314]
when i add new query with (+) of non exciting man i got an alert and went to main (and thats ok!) but then i can get back to it with back button .. i dont think it's right.. 
http://imgur.com/a/pb7n7

**Comment by SlasherTech** [comment]
We are working on.
Thanks

**Comment by shaysegal** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10211960-204257602_3-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by SlasherTech** [comment]
Hi , I tried to recreate your problem but I couldn't.
Can you specify your parameters ?
