### ISSUE TITLE
query doesnt work

### ISSUE THREAD

**Issue by tanyabrokhman** [TechnionYP5777/Info-Evaluation#315]
I searched for the following:
Life
Tatiana Romanova
I get an error that the person doesnt exist. Well, she did exist :)
https://en.wikipedia.org/wiki/Grand_Duchess_Tatiana_Nikolaevna_of_Russia

**Comment by SlasherTech** [comment]
The problem was a forgotten "toLowerCase" function. (which changed the name of the person)
It should work now.
