### ISSUE TITLE
Arrests

### ISSUE THREAD

**Issue by tanyabrokhman** [TechnionYP5777/Info-Evaluation#320]
Input = Maddonna (intertainer)
I guess she has no arrests but you should add a msg saying that, not just leave the screen empty

**Comment by SlasherTech** [comment]
If you entered "Maddonna" it wont work because its spelled wrong.
However, the indeed if soeone has no arrests then it won't alert you because we decided to still show the personal information of this person.

**Comment by tanyabrokhman** [comment]
![image](https://user-images.githubusercontent.com/25345526/27789495-91c8a63e-5ff5-11e7-9196-e786567fb75c.png)
you should add at the bottom of the screen "No arrests". And I didnt misspell it in the app. just here :)
