### ISSUE TITLE
Understandable Order

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Info-Evaluation#321]
When I look for people born before 1950, I get this confusing output, ordered randomly it seems. The order should match the query at hand - in this case, I think the order should be by date of birth.

![screenshot 01_21pm jul 03 2017](https://user-images.githubusercontent.com/16455692/27789136-076e58ae-5ff4-11e7-91c4-e6ca2b3c0f46.png)

That means:
- If order alphabetically by first name: Yisrael should appear before Yoav.
- If by surname: Yoav should appear before Amos.
- If by date of birth, as I expected: Yisrael should appear before Yoav.

**Comment by SlasherTech** [comment]
This order of the output is by DBpedia's order. We did not change it.
