### ISSUE TITLE
Loading massage didn't disappear when data loaded

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/Info-Evaluation#322]
when entering to immigrated there is a spinner and then message but when the data is loaded the message didn't dissappear
![19749745_1802688823079817_1925453350_o](https://user-images.githubusercontent.com/23156121/27789450-51545058-5ff5-11e7-9a5f-fad94aa13ad5.png)

**Comment by SlasherTech** [comment]
you need to click OK
