### ISSUE TITLE
Fetching Error in Awards

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/Info-Evaluation#324]
when inserting "koral" in Awards section and pressing on Alexander Koral there is a fetching error.
So why to show this option as available? 
![19688395_1802715326410500_354545617_o](https://user-images.githubusercontent.com/23156121/27790476-355fa844-5ff9-11e7-904f-1dc8b8b412a2.png)

**Comment by NetanelFelcher** [comment]
The options that are shown are taken from wikipedia suggestions. If a person appears on the list it means he has a wikipedia page. It does not mean it has a dBpedia entry necessarily, and the extra information is taken from DBpedia
