### ISSUE TITLE
Ambiguity resolution isn't filtered

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Info-Evaluation#325]
For example, when I look for awards for an Eli, I get the Eviromental Law Institute, which doesn't have any awards to its name.
![screenshot_2017-07-03-14-03-40](https://user-images.githubusercontent.com/16455692/27790360-cd09fa60-5ff8-11e7-8e37-10a025409ed1.png)
So when I click it I get:
![screenshot_2017-07-03-14-03-27](https://user-images.githubusercontent.com/16455692/27790361-cff810d6-5ff8-11e7-9b88-f2fe8ac66882.png)

I think the ambiguity suggestions should include only items that have the necessary information in them: if I'm looking for awards of actor Eli Wallach and can't remember his last name, I shouldn't have to filter entities that don't have any awards to resolve my ambiguity.

**Comment by yosefraisman** [comment]
I shouldn't get cities, programming languages and disambiguation files either.

**Comment by SlasherTech** [comment]
Hi,
We do not filter it because filtering it means checking the query for each of them which will lead to a long waiting time to the user.
Therefore, we do not filter the list.
