### ISSUE TITLE
Create a Connection to MySQL Server

### ISSUE THREAD

**Issue by osherh** [TechnionYP5777/Info-Evaluation#47]

**Comment by yossigil** [comment]
Start thinking about testing and dependency injection

**Comment by osherh** [comment]
We could not convert it to use Mockito and DI in time, so we have decided to move it to Sprint 2

**Comment by yossigil** [comment]
@yh-github : FYI. 
@osherh : do you have an issue on this?

**Comment by osherh** [comment]
yes see issue #53
