### ISSUE TITLE
Continuous work on the Analysis part

### ISSUE THREAD

**Issue by SlasherTech** [TechnionYP5777/Info-Evaluation#61]
We will continue working on the Analysis part.

This work will include:
- Adding more formats of paragraphs.
-Exctracting the name of the person in a more accurate manner.
-Exctracting the reason of the incident in a more detailed manner.
-Add the possibility for the user to add suggestions to the information available to the project.

**Comment by osherh** [comment]
You better split this issue into 3.

**Comment by SlasherTech** [comment]
@osherh  Thank you for the advice, but this issue is meant to track all the work done on the analysis part of sprint 2.

**Comment by yh-github** [comment]
Please note the submission date is January 16 and the focus should be on user interaction.

**Comment by SlasherTech** [comment]
@yh-github Is it possible , that by any chance you mean January 23 ? It was always stated that sprint 2 is due by January 23 .


Thank you.
@osherh @NetanelFelcher @geniashand @ward-mattar @viviansh

**Comment by yh-github** [comment]
January 16 in the date table (the course website). Where was the 23rd mentioned?

**Comment by SlasherTech** [comment]
We said it in our meeting and also it's defined as the deadline for all the other projects on their milestones on github.

**Comment by SlasherTech** [comment]
Done for this sprint : 
- Accurate name extraction

- Adding date formates and fixing bugs in dates extraction.

- Enhanced "static" analysis.

- Using OpenIE for interactive analysis , letting the user choose the reason from a list of possible reasons.

- Adding key words for reasons in order to improve filtering options.
