### ISSUE TITLE
Find Key words in the reason

### ISSUE THREAD

**Issue by NetanelFelcher** [TechnionYP5777/Info-Evaluation#70]
finding the key words by counting the number of occurrences .

A word is a key word if it appears in more than one reason.

Relation words (in, on, for etc.) are not key words.

After finding the key words we will have more options of sorting and refining the results.

**Comment by geniashand** [comment]
@NetanelFelcher 
The call to findKeyWords() in AnalyzeSources is problematic. Words are counted multiple times. We should consider a different solution
