### ISSUE TITLE
Load previous results

### ISSUE THREAD

**Issue by osherh** [TechnionYP5777/Info-Evaluation#84]

**Comment by SlasherTech** [comment]
@osherh What is the purpose of this issue ?

**Comment by osherh** [comment]
@MosheEliasof , basically it's an undo feature. Since every operation(sort/filter) its performed on the output of the previous one(unless a refresh was made), we give the user an option to restore the results of the last operation performed. This issue give support from the DB side to the undo feature - meaning, manging the tables and stack after each operation.

**Comment by osherh** [comment]
we've decided to move it to sprint 3
